print "Exception has occured";
halt;
